# -*- coding: utf-8 -*-
"""SQL GENERATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmzHcdiDj38XUf1tq-Z9RY34pJA1KH56
"""

pip install -U transformers

from transformers import pipeline
pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages =[
    {"role": "user","content":"who are you?"},
]
pipe(messages)

from transformers import AutoTokenizer,AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model =AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages =[
    {"role": "user","content":"who are you?"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_genration_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt"
).to(model.device)

outputs = model.generate(**inputs,max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

pip install -q gradio transformers torch black autopep8 reportlab requests

!pip install reportlab

!pip install gradio reportlab

# ==========================================================
# SQL QUERY GENERATOR - PURE BLACK/WHITE FONT FIX ONLY
# ==========================================================

!pip install -q gradio transformers torch reportlab requests

import gradio as gr
import re
import urllib.parse
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch

SCHEMA = {
    "users": ["id","name","email","signup_date","age","country","status"],
    "orders": ["id","user_id","product_name","amount","order_date","status"],
    "products": ["id","name","price","category","stock"],
    "transactions": ["id","user_id","amount","date","type"]
}

DANGEROUS_KEYWORDS = ['DROP','DELETE','ALTER','TRUNCATE','INSERT','UPDATE','EXEC','EXECUTE']
DANGEROUS_PATTERNS = [';','--','/*','*/','xp_','sp_']

def is_safe(text):
    text_upper = text.upper()
    for keyword in DANGEROUS_KEYWORDS:
        if keyword in text_upper:
            return False
    for pattern in DANGEROUS_PATTERNS:
        if pattern in text:
            return False
    return True

def get_table_name(query):
    query = query.lower()
    mapping = {
        "users":["user","customer","account","profile"],
        "orders":["order","purchase","buy"],
        "products":["product","item","goods"],
        "transactions":["transaction","payment","transfer"]
    }
    for table, words in mapping.items():
        for word in words:
            if word in query:
                return table
    return None

def extract_conditions(query):
    query = query.lower()
    conditions = []
    if "last month" in query:
        conditions.append("DATE(signup_date) >= DATE('now','-1 month')")
    if "last week" in query:
        conditions.append("DATE(date) >= DATE('now','-7 days')")
    if "last year" in query:
        conditions.append("DATE(signup_date) >= DATE('now','-1 year')")
    amount_match = re.search(r'(greater than|more than|above)\s+(\d+)', query)
    if amount_match:
        conditions.append(f"amount > {amount_match.group(2)}")
    return conditions

query_history = []

def generate_sql(user_input):
    if not user_input.strip():
        return "⚠ Please enter a query."
    if not is_safe(user_input):
        return "❌ Security Alert: Unsafe SQL detected."
    table = get_table_name(user_input)
    if not table:
        return "⚠ Could not detect table."

    sql = f"SELECT * FROM {table}"
    conditions = extract_conditions(user_input)
    if conditions:
        sql += " WHERE " + " AND ".join(conditions)
    sql += " LIMIT 10;"

    query_history.append({
        "user": user_input,
        "sql": sql,
        "timestamp": datetime.now().isoformat()
    })
    return sql

def whatsapp_share():
    if not query_history:
        return "No queries available."
    message = "📊 SQL Queries Generated:\n\n"
    for i,q in enumerate(query_history[-5:],1):
        message += f"{i}. {q['sql']}\n\n"
    return "https://wa.me/?text=" + urllib.parse.quote(message)

def facebook_share():
    if not query_history:
        return "No queries available."
    message = "SQL Queries:\n\n"
    for q in query_history[-3:]:
        message += f"{q['sql']}\n"
    return "https://www.facebook.com/sharer/sharer.php?u=" + urllib.parse.quote(message)

def export_pdf():
    if not query_history:
        return None
    filename = f"SQL_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph("SQL Query Report", styles["Heading1"]))
    story.append(Spacer(1,0.3*inch))
    for i,q in enumerate(query_history,1):
        story.append(Paragraph(f"<b>Query {i}</b>", styles["Heading2"]))
        story.append(Paragraph(q["sql"], styles["Normal"]))
        story.append(Spacer(1,0.3*inch))
    doc.build(story)
    return filename

def export_txt():
    if not query_history:
        return None
    filename = f"SQL_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    with open(filename,"w") as f:
        for i,q in enumerate(query_history,1):
            f.write(f"{i}. {q['sql']}\n\n")
    return filename

def clear_history():
    query_history.clear()
    return ""

# ==========================================================
# UNIVERSAL BLACK/WHITE FONT FIX
# ==========================================================
custom_css = """

body, .gradio-container {
    background: linear-gradient(135deg, #0b1120, #1e293b) !important;
}

/* Headings white */
h1, h2, h3, h4, p, label {
    color: #ffffff !important;
}

/* All boxes mild black */
.gr-box,
.gr-panel,
.gr-code,
.cm-editor,
textarea,
input,
.gr-file {
    background-color: #1f1f1f !important;
    color: #ffffff !important;
}

/* Code text */
.cm-content, .cm-line {
    color: #ffffff !important;
}

/* File text */
.gr-file * {
    color: #ffffff !important;
}

/* Schema subtext white strong */
.gr-markdown ul,
.gr-markdown li {
    color: #ffffff !important;
}

/* Buttons */
button {
    background: linear-gradient(90deg, #3b82f6, #2563eb) !important;
    color: #ffffff !important;
    border-radius: 10px !important;
    border: none !important;
    height: 45px !important;
}

"""

with gr.Blocks(theme=gr.themes.Base(), css=custom_css) as demo:

    gr.Markdown("# 🔎 SQL Query Generator")
    gr.Markdown("### Natural Language → SQLite SQL")
    gr.Markdown("Convert plain English requests into safe, production-ready SQL queries!")

    with gr.Row():
        with gr.Column(scale=3):
            sql_output = gr.Code(label="Query Conversion", language="sql", lines=18)
            user_input = gr.Textbox(label="Natural Language Request")
            generate_btn = gr.Button("Generate SQL")

        with gr.Column(scale=1):
            gr.Markdown("## Controls")
            clear_btn = gr.Button("Clear History")

            gr.Markdown("## Share")
            wa_btn = gr.Button("WhatsApp")
            fb_btn = gr.Button("Facebook")
            share_box = gr.Textbox(label="Share Link")

            gr.Markdown("---")

            gr.Markdown("## 📊 Schema Info")
            gr.Markdown("""
**Tables:**
- users
- orders
- products
- transactions
""")

            gr.Markdown("---")

            gr.Markdown("## Export")
            pdf_btn = gr.Button("Download PDF")
            txt_btn = gr.Button("Download TXT")
            pdf_file = gr.File(label="PDF File")
            txt_file = gr.File(label="TXT File")

    generate_btn.click(generate_sql, user_input, sql_output)
    clear_btn.click(clear_history, outputs=sql_output)
    wa_btn.click(whatsapp_share, outputs=share_box)
    fb_btn.click(facebook_share, outputs=share_box)
    pdf_btn.click(export_pdf, outputs=pdf_file)
    txt_btn.click(export_txt, outputs=txt_file)

demo.launch(share=True)